# Generated by Django 3.2.5 on 2021-07-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velorentapp', '0002_auto_20210731_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='description',
            field=models.TextField(verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='day',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hour',
            name='description',
            field=models.TextField(verbose_name='Hour'),
        ),
        migrations.AlterField(
            model_name='hour',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='description',
            field=models.TextField(verbose_name='Week'),
        ),
        migrations.AlterField(
            model_name='week',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
