# Generated by Django 3.2.5 on 2021-07-31 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velorentapp', '0003_auto_20210731_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hour',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='week',
            name='price',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
